import Head from "next/head";
import { useState } from "react";
import { useAuth } from "../utils/context/AuthContext";

export default function SignIn() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const { login, currentUser } = useAuth();

  
  const handleSignIn = () => {
    
  }
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="relative py-16">
          <div className="container relative m-auto px-6 text-gray-500 md:px-12 xl:px-40">
            <div className="m-auto md:w-8/12 lg:w-6/12 xl:w-6/12">
              <div className="rounded-3xl border border-gray-100 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-2xl shadow-gray-600/10 dark:shadow-none">
                <div className="p-8 py-8 sm:p-16">
                  <div className="space-y-4">
                    {/* <img
                      src="images/icon.svg"
                      loading="lazy"
                      className="w-10"
                      alt="tailus logo"
                    /> */}
                    <h2 className="mb-8 text-2xl font-bold text-gray-800 dark:text-white">
                      Sign in to unlock the <br />
                      best of DesignPage.
                    </h2>
                  </div>
                  
                  {/* Form start */}
                  <div className="mt-16 grid space-y-4">
                    <div>
                      <label htmlFor="email" className="sr-only">
                        Email
                      </label>

                      <div className="relative">
                        <input
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                          type="email"
                          className="w-full p-4 pr-12 text-base border-solid border-2 border-gray-200 rounded-lg"
                          placeholder="Enter email"
                        />
                      </div>
                    </div>

                    <div>
                      <label htmlFor="password" className="sr-only">
                        Password
                      </label>
                      <div className="relative">
                        <input
                          value={password}
                          onChange={(e) => setPassword(e.target.value)}
                          type="password"
                          className="w-full p-4 pr-12 text-base border-solid border-2 border-gray-200 rounded-lg"
                          placeholder="Enter password"
                        />
                      </div>
                    </div>

                    {/* SignIn Button */}
                    <button onClick={handleSignIn} className="bg-sky-400 h-11 items-center px-6  rounded-full border border-gray-200 ">
                      <span className="w-full justify-center items-center gap-3 text-base font-medium text-gray-900 dark:text-gray-200">
                        SignIn
                      </span>
                    </button>
                  </div>

                  <div className="mt-32 space-y-4 text-center text-gray-600 dark:text-gray-400 sm:-mb-8">
                    <p className="text-xs">
                      By proceeding, you agree to our{" "}
                      <a href="#" className="underline">
                        Terms of Use
                      </a>{" "}
                      and confirm you have read our
                      <a href="#" className="underline">
                        Privacy and Cookie Statement
                      </a>
                      .
                    </p>
                    <p className="text-xs">
                      This site is protected by reCAPTCHA and the
                      <a href="#" className="underline">
                        Google Privacy Policy
                      </a>{" "}
                      and
                      <a href="#" className="underline">
                        Terms of Service
                      </a>{" "}
                      apply.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
